export const Roles = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  USER: 'USER',
  SALES_REP: 'SALES_REP',
  ACCOUNTANT: 'ACCOUNTANT',
  HR_MANAGER: 'HR_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  PROCUREMENT_MANAGER: 'PROCUREMENT_MANAGER',
};

export const Permissions = {
  // User Management
  CREATE_USER: 'CREATE_USER',
  READ_USERS: 'READ_USERS',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',

  // Product Management
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  READ_PRODUCTS: 'READ_PRODUCTS',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  ADJUST_STOCK: 'ADJUST_STOCK',

  // Sales Management
  CREATE_ORDER: 'CREATE_ORDER',
  READ_ORDERS: 'READ_ORDERS',
  UPDATE_ORDER: 'UPDATE_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',

  // Purchasing Management
  CREATE_PURCHASE_ORDER: 'CREATE_PURCHASE_ORDER',
  READ_PURCHASE_ORDERS: 'READ_PURCHASE_ORDERS',
  UPDATE_PURCHASE_ORDER: 'UPDATE_PURCHASE_ORDER',
  DELETE_PURCHASE_ORDER: 'DELETE_PURCHASE_ORDER',

  // Financial Management
  CREATE_TRANSACTION: 'CREATE_TRANSACTION',
  READ_TRANSACTIONS: 'READ_TRANSACTIONS',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION',

  // HR Management
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  READ_EMPLOYEES: 'READ_EMPLOYEES',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  APPROVE_LEAVE: 'APPROVE_LEAVE',

  // Reports
  GENERATE_REPORTS: 'GENERATE_REPORTS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',

  // System Administration
  SYSTEM_CONFIG: 'SYSTEM_CONFIG',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
};

export const AuditEvents = {
  // Authentication Events
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',
  SECURITY_VIOLATION: 'SECURITY_VIOLATION',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',

  // User Management Events
  USER_CREATED: 'USER_CREATED',
  USER_CREATION_FAILED: 'USER_CREATION_FAILED',
  USER_CREATION_ERROR: 'USER_CREATION_ERROR',
  USER_UPDATED: 'USER_UPDATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  WEAK_PASSWORD_ATTEMPT: 'WEAK_PASSWORD_ATTEMPT',
  INVALID_PASSWORD_CHANGE_ATTEMPT: 'INVALID_PASSWORD_CHANGE_ATTEMPT',
  PASSWORD_CHANGED: 'PASSWORD_CHANGED',

  // Product Management Events
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  STOCK_ADJUSTED: 'STOCK_ADJUSTED',
  STOCK_UPDATED: 'STOCK_UPDATED',
  LOW_STOCK_ALERT: 'LOW_STOCK_ALERT',

  // Sales Events
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_UPDATED: 'ORDER_UPDATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  INVOICE_GENERATED: 'INVOICE_GENERATED',

  // Purchasing Events
  PURCHASE_ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
  PURCHASE_ORDER_UPDATED: 'PURCHASE_ORDER_UPDATED',
  PURCHASE_ORDER_APPROVED: 'PURCHASE_ORDER_APPROVED',
  SUPPLIER_CREATED: 'SUPPLIER_CREATED',

  // Financial Events
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_UPDATED: 'TRANSACTION_UPDATED',
  PAYMENT_PROCESSED: 'PAYMENT_PROCESSED',

  // HR Events
  EMPLOYEE_CREATED: 'EMPLOYEE_CREATED',
  EMPLOYEE_UPDATED: 'EMPLOYEE_UPDATED',
  LEAVE_REQUESTED: 'LEAVE_REQUESTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',

  // System Events
  SYSTEM_BACKUP: 'SYSTEM_BACKUP',
  SYSTEM_RESTORE: 'SYSTEM_RESTORE',
  DATA_EXPORT: 'DATA_EXPORT',
  DATA_IMPORT: 'DATA_IMPORT',
};

export const PaginationDefaults = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};

export const CacheKeys = {
  USERS: 'users',
  PRODUCTS: 'products',
  CATEGORIES: 'categories',
  ORDERS: 'orders',
  SUPPLIERS: 'suppliers',
  EMPLOYEES: 'employees',
};

export const ErrorMessages = {
  GENERIC_ERROR: 'An unexpected error occurred. Please try again.',
  NOT_FOUND: 'Resource not found.',
  UNAUTHORIZED: 'Unauthorized access.',
  FORBIDDEN: 'Insufficient permissions.',
  VALIDATION_ERROR: 'Validation failed.',
  DUPLICATE_ENTRY: 'Resource already exists.',
  DATABASE_ERROR: 'Database operation failed.',
  NETWORK_ERROR: 'Network error occurred.',
};

export const SuccessMessages = {
  CREATED: 'Resource created successfully.',
  UPDATED: 'Resource updated successfully.',
  DELETED: 'Resource deleted successfully.',
  PROCESSED: 'Operation processed successfully.',
};